org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.186
neo_version_range=[21.1.186,)
loader_version_range=[1,)
mod_id=stonecraft
mod_name=StoneCraft
mod_license=BSD-3-Clause
mod_version=1.0.0
mod_group_id=ctn.stonecraft
mod_authors=XiaoJin,NewBee,MCcaptain5412,AmarokIce
mod_description=Are you still troubled by the pile of round stones in the mining box? This mod can help you solve poverty in the early stages of the game!
jei_version=19.21.1.308
#org.gradle.java.home=C:\\Users\\wang_\\.jdks\\jbr-21.0.7