package ctn.stonecraft.datagen.tag;

import ctn.stonecraft.datagen.ScTags;
import ctn.stonecraft.init.ScBlocks;
import ctn.stonecraft.init.ScItems;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.NotNull;

import javax.annotation.CheckForNull;
import java.util.concurrent.CompletableFuture;

import static ctn.stonecraft.core.StoneCraft.ID;
import static ctn.stonecraft.datagen.ScTags.ScBlocks.FUNCTIONAL_BLOCKS;
import static ctn.stonecraft.datagen.ScTags.ScItems.*;
import static net.minecraft.tags.ItemTags.*;
import static net.minecraft.world.item.Items.*;

public class ScItemTags extends ItemTagsProvider {
	public ScItemTags(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider,
			CompletableFuture<TagLookup<Block>> blockTags, @CheckForNull ExistingFileHelper existingFileHelper) {
		super(output, lookupProvider, blockTags, ID, existingFileHelper);
	}

	@Override
	protected void addTags(HolderLookup.@NotNull Provider capability) {
		tag(COMPRESSED_STONE_HELMET_LV1).add(ScItems.COMPRESSED_STONE_HELMET_LV1.get());
		tag(COMPRESSED_STONE_HELMET_LV2).add(ScItems.COMPRESSED_STONE_HELMET_LV2.get());
		tag(COMPRESSED_STONE_HELMET_LV3).add(ScItems.COMPRESSED_STONE_HELMET_LV3.get());
		tag(COMPRESSED_STONE_HELMET_LV4).add(ScItems.COMPRESSED_STONE_HELMET_LV4.get());
		tag(COMPRESSED_STONE_HELMET_LV5).add(ScItems.COMPRESSED_STONE_HELMET_LV5.get());
		tag(COMPRESSED_STONE_HELMET).addTags(
				COMPRESSED_STONE_HELMET_LV1,
				COMPRESSED_STONE_HELMET_LV2,
				COMPRESSED_STONE_HELMET_LV3,
				COMPRESSED_STONE_HELMET_LV4,
				COMPRESSED_STONE_HELMET_LV5);
		tag(STONE_HELMET).addTag(COMPRESSED_STONE_HELMET).add(ScItems.STONE_HELMET.get());

		tag(COMPRESSED_STONE_CHESTPLATE_LV1).add(ScItems.COMPRESSED_STONE_CHESTPLATE_LV1.get());
		tag(COMPRESSED_STONE_CHESTPLATE_LV2).add(ScItems.COMPRESSED_STONE_CHESTPLATE_LV2.get());
		tag(COMPRESSED_STONE_CHESTPLATE_LV3).add(ScItems.COMPRESSED_STONE_CHESTPLATE_LV3.get());
		tag(COMPRESSED_STONE_CHESTPLATE_LV4).add(ScItems.COMPRESSED_STONE_CHESTPLATE_LV4.get());
		tag(COMPRESSED_STONE_CHESTPLATE_LV5).add(ScItems.COMPRESSED_STONE_CHESTPLATE_LV5.get());
		tag(COMPRESSED_STONE_CHESTPLATE).addTags(
				COMPRESSED_STONE_CHESTPLATE_LV1,
				COMPRESSED_STONE_CHESTPLATE_LV2,
				COMPRESSED_STONE_CHESTPLATE_LV3,
				COMPRESSED_STONE_CHESTPLATE_LV4,
				COMPRESSED_STONE_CHESTPLATE_LV5);
		tag(STONE_CHESTPLATE).addTag(COMPRESSED_STONE_CHESTPLATE).add(ScItems.STONE_CHESTPLATE.get());

		tag(COMPRESSED_STONE_LEGGINGS_LV1).add(ScItems.COMPRESSED_STONE_LEGGINGS_LV1.get());
		tag(COMPRESSED_STONE_LEGGINGS_LV2).add(ScItems.COMPRESSED_STONE_LEGGINGS_LV2.get());
		tag(COMPRESSED_STONE_LEGGINGS_LV3).add(ScItems.COMPRESSED_STONE_LEGGINGS_LV3.get());
		tag(COMPRESSED_STONE_LEGGINGS_LV4).add(ScItems.COMPRESSED_STONE_LEGGINGS_LV4.get());
		tag(COMPRESSED_STONE_LEGGINGS_LV5).add(ScItems.COMPRESSED_STONE_LEGGINGS_LV5.get());
		tag(COMPRESSED_STONE_LEGGINGS).addTags(
				COMPRESSED_STONE_LEGGINGS_LV1,
				COMPRESSED_STONE_LEGGINGS_LV2,
				COMPRESSED_STONE_LEGGINGS_LV3,
				COMPRESSED_STONE_LEGGINGS_LV4,
				COMPRESSED_STONE_LEGGINGS_LV5);
		tag(STONE_LEGGINGS).addTag(COMPRESSED_STONE_LEGGINGS).add(ScItems.STONE_LEGGINGS.get());

		tag(COMPRESSED_STONE_BOOTS_LV1).add(ScItems.COMPRESSED_STONE_BOOTS_LV1.get());
		tag(COMPRESSED_STONE_BOOTS_LV2).add(ScItems.COMPRESSED_STONE_BOOTS_LV2.get());
		tag(COMPRESSED_STONE_BOOTS_LV3).add(ScItems.COMPRESSED_STONE_BOOTS_LV3.get());
		tag(COMPRESSED_STONE_BOOTS_LV4).add(ScItems.COMPRESSED_STONE_BOOTS_LV4.get());
		tag(COMPRESSED_STONE_BOOTS_LV5).add(ScItems.COMPRESSED_STONE_BOOTS_LV5.get());
		tag(COMPRESSED_STONE_BOOTS).addTags(
				COMPRESSED_STONE_BOOTS_LV1,
				COMPRESSED_STONE_BOOTS_LV2,
				COMPRESSED_STONE_BOOTS_LV3,
				COMPRESSED_STONE_BOOTS_LV4,
				COMPRESSED_STONE_BOOTS_LV5);
		tag(STONE_BOOTS).addTag(COMPRESSED_STONE_BOOTS).add(ScItems.STONE_BOOTS.get());

		tag(COMPRESSED_STONE_ARMOR_LV1).addTags(
				COMPRESSED_STONE_HELMET_LV1,
				COMPRESSED_STONE_CHESTPLATE_LV1,
				COMPRESSED_STONE_LEGGINGS_LV1,
				COMPRESSED_STONE_BOOTS_LV1);
		tag(COMPRESSED_STONE_ARMOR_LV2).addTags(
				COMPRESSED_STONE_HELMET_LV2,
				COMPRESSED_STONE_CHESTPLATE_LV2,
				COMPRESSED_STONE_LEGGINGS_LV2,
				COMPRESSED_STONE_BOOTS_LV2);
		tag(COMPRESSED_STONE_ARMOR_LV3).addTags(
				COMPRESSED_STONE_HELMET_LV3,
				COMPRESSED_STONE_CHESTPLATE_LV3,
				COMPRESSED_STONE_LEGGINGS_LV3,
				COMPRESSED_STONE_BOOTS_LV3);
		tag(COMPRESSED_STONE_ARMOR_LV4).addTags(
				COMPRESSED_STONE_HELMET_LV4,
				COMPRESSED_STONE_CHESTPLATE_LV4,
				COMPRESSED_STONE_LEGGINGS_LV4,
				COMPRESSED_STONE_BOOTS_LV4);
		tag(COMPRESSED_STONE_ARMOR_LV5).addTags(
				COMPRESSED_STONE_HELMET_LV5,
				COMPRESSED_STONE_CHESTPLATE_LV5,
				COMPRESSED_STONE_LEGGINGS_LV5,
				COMPRESSED_STONE_BOOTS_LV5);
		tag(COMPRESSED_STONE_ARMOR).addTags(
				COMPRESSED_STONE_ARMOR_LV1,
				COMPRESSED_STONE_ARMOR_LV2,
				COMPRESSED_STONE_ARMOR_LV3,
				COMPRESSED_STONE_ARMOR_LV4,
				COMPRESSED_STONE_ARMOR_LV5);
		tag(STONE_ARMOR).addTag(COMPRESSED_STONE_ARMOR);

		tag(FOOT_ARMOR).addTag(STONE_BOOTS);
		tag(LEG_ARMOR).addTag(STONE_LEGGINGS);
		tag(CHEST_ARMOR).addTag(STONE_CHESTPLATE);
		tag(HEAD_ARMOR).addTag(STONE_HELMET);
		tag(TRIMMABLE_ARMOR).addTag(STONE_ARMOR);

		tag(COMPRESSED_STONE_TOOL_LV1).add(
				ScItems.COMPRESSED_STONE_SWORD_LV1.get(),
				ScItems.COMPRESSED_STONE_AXE_LV1.get(),
				ScItems.COMPRESSED_STONE_PICKAXE_LV1.get(),
				ScItems.COMPRESSED_STONE_SHOVEL_LV1.get(),
				ScItems.COMPRESSED_STONE_HOE_LV1.get()
		);
		tag(COMPRESSED_STONE_TOOL_LV2).add(
				ScItems.COMPRESSED_STONE_SWORD_LV2.get(),
				ScItems.COMPRESSED_STONE_AXE_LV2.get(),
				ScItems.COMPRESSED_STONE_PICKAXE_LV2.get(),
				ScItems.COMPRESSED_STONE_SHOVEL_LV2.get(),
				ScItems.COMPRESSED_STONE_HOE_LV2.get()
		);
		tag(COMPRESSED_STONE_TOOL_LV3).add(
				ScItems.COMPRESSED_STONE_SWORD_LV3.get(),
				ScItems.COMPRESSED_STONE_AXE_LV3.get(),
				ScItems.COMPRESSED_STONE_PICKAXE_LV3.get(),
				ScItems.COMPRESSED_STONE_SHOVEL_LV3.get(),
				ScItems.COMPRESSED_STONE_HOE_LV3.get()
		);
		tag(COMPRESSED_STONE_TOOL_LV4).add(
				ScItems.COMPRESSED_STONE_SWORD_LV4.get(),
				ScItems.COMPRESSED_STONE_AXE_LV4.get(),
				ScItems.COMPRESSED_STONE_PICKAXE_LV4.get(),
				ScItems.COMPRESSED_STONE_SHOVEL_LV4.get(),
				ScItems.COMPRESSED_STONE_HOE_LV4.get()
		);
		tag(COMPRESSED_STONE_TOOL_LV5).add(
				ScItems.COMPRESSED_STONE_SWORD_LV5.get(),
				ScItems.COMPRESSED_STONE_AXE_LV5.get(),
				ScItems.COMPRESSED_STONE_PICKAXE_LV5.get(),
				ScItems.COMPRESSED_STONE_SHOVEL_LV5.get(),
				ScItems.COMPRESSED_STONE_HOE_LV5.get(),
				ScItems.ULTIMATE_COMPRESSED_STONE_SWORD_ACT1.get(),
				ScItems.ULTIMATE_COMPRESSED_STONE_SWORD_ACT2.get(),
				ScItems.ULTIMATE_COMPRESSED_STONE_SWORD_ACT3.get()
		);
		tag(VERSATILE_COMPRESSED_STONE_TOOL).add(
				ScItems.VERSATILE_COMPRESSED_STONE_TOOL_LV1.get(),
				ScItems.VERSATILE_COMPRESSED_STONE_TOOL_LV2.get(),
				ScItems.VERSATILE_COMPRESSED_STONE_TOOL_LV3.get(),
				ScItems.VERSATILE_COMPRESSED_STONE_TOOL_LV4.get(),
				ScItems.VERSATILE_COMPRESSED_STONE_TOOL_LV5.get()
		);
		tag(VERSATILE_STONE_TOOL)
				.addTag(VERSATILE_COMPRESSED_STONE_TOOL)
				.add(ScItems.VERSATILE_STONE_TOOL.get());
		tag(ULTIMATE_COMPRESSED_SWORD_TOOL).add(
				ScItems.ULTIMATE_COMPRESSED_STONE_SWORD_ACT1.get(),
				ScItems.ULTIMATE_COMPRESSED_STONE_SWORD_ACT2.get(),
				ScItems.ULTIMATE_COMPRESSED_STONE_SWORD_ACT3.get()
		);
		tag(COMPRESSED_SWORD_TOOL)
				.addTag(ULTIMATE_COMPRESSED_SWORD_TOOL)
				.add(
						ScItems.COMPRESSED_STONE_SWORD_LV1.get(),
						ScItems.COMPRESSED_STONE_SWORD_LV2.get(),
						ScItems.COMPRESSED_STONE_SWORD_LV3.get(),
						ScItems.COMPRESSED_STONE_SWORD_LV4.get(),
						ScItems.COMPRESSED_STONE_SWORD_LV5.get()
				);
		tag(COMPRESSED_AXE_TOOL)
				.addTag(VERSATILE_COMPRESSED_STONE_TOOL)
				.add(
						ScItems.COMPRESSED_STONE_AXE_LV1.get(),
						ScItems.COMPRESSED_STONE_AXE_LV2.get(),
						ScItems.COMPRESSED_STONE_AXE_LV3.get(),
						ScItems.COMPRESSED_STONE_AXE_LV4.get(),
						ScItems.COMPRESSED_STONE_AXE_LV5.get()
				);
		tag(COMPRESSED_PICKAXE_TOOL)
				.addTag(VERSATILE_COMPRESSED_STONE_TOOL)
				.add(
						ScItems.COMPRESSED_STONE_PICKAXE_LV1.get(),
						ScItems.COMPRESSED_STONE_PICKAXE_LV2.get(),
						ScItems.COMPRESSED_STONE_PICKAXE_LV3.get(),
						ScItems.COMPRESSED_STONE_PICKAXE_LV4.get(),
						ScItems.COMPRESSED_STONE_PICKAXE_LV5.get()
				);
		tag(COMPRESSED_SHOVEL_TOOL)
				.addTag(VERSATILE_COMPRESSED_STONE_TOOL)
				.add(
						ScItems.COMPRESSED_STONE_SHOVEL_LV1.get(),
						ScItems.COMPRESSED_STONE_SHOVEL_LV2.get(),
						ScItems.COMPRESSED_STONE_SHOVEL_LV3.get(),
						ScItems.COMPRESSED_STONE_SHOVEL_LV4.get(),
						ScItems.COMPRESSED_STONE_SHOVEL_LV5.get()
				);
		tag(COMPRESSED_HOE_TOOL)
				.addTag(VERSATILE_COMPRESSED_STONE_TOOL)
				.add(
						ScItems.COMPRESSED_STONE_HOE_LV1.get(),
						ScItems.COMPRESSED_STONE_HOE_LV2.get(),
						ScItems.COMPRESSED_STONE_HOE_LV3.get(),
						ScItems.COMPRESSED_STONE_HOE_LV4.get(),
						ScItems.COMPRESSED_STONE_HOE_LV5.get()
				);
		tag(COMPRESSED_STONE_TOOL).addTags(
				COMPRESSED_SWORD_TOOL,
				COMPRESSED_AXE_TOOL,
				COMPRESSED_PICKAXE_TOOL,
				COMPRESSED_SHOVEL_TOOL,
				COMPRESSED_HOE_TOOL
		);
		tag(ItemTags.SWORDS).addTag(COMPRESSED_SWORD_TOOL);
		tag(ItemTags.AXES).addTags(
				COMPRESSED_AXE_TOOL,
				VERSATILE_STONE_TOOL
		);
		tag(ItemTags.PICKAXES).addTags(
				COMPRESSED_PICKAXE_TOOL,
				VERSATILE_STONE_TOOL
		);
		tag(ItemTags.CLUSTER_MAX_HARVESTABLES).addTags(
				COMPRESSED_PICKAXE_TOOL,
				VERSATILE_STONE_TOOL
		);
		tag(Tags.Items.MINING_TOOL_TOOLS).addTags(
				COMPRESSED_PICKAXE_TOOL,
				VERSATILE_STONE_TOOL
		);
		tag(Tags.Items.MELEE_WEAPON_TOOLS).addTags(
				COMPRESSED_SWORD_TOOL,
				COMPRESSED_AXE_TOOL
		);
		tag(ItemTags.SHOVELS).addTags(
				COMPRESSED_SHOVEL_TOOL,
				VERSATILE_STONE_TOOL
		);
		tag(ItemTags.HOES).addTags(
				COMPRESSED_HOE_TOOL,
				VERSATILE_STONE_TOOL
		);
		tag(Tags.Items.TOOLS).addTags(
				COMPRESSED_STONE_TOOL,
				VERSATILE_STONE_TOOL
		);
		copy(ScTags.ScBlocks.COMPRESSED_BLOCK_LV1, COMPRESSED_BLOCK_LV1);
		copy(ScTags.ScBlocks.COMPRESSED_BLOCK_LV2, COMPRESSED_BLOCK_LV2);
		copy(ScTags.ScBlocks.COMPRESSED_BLOCK_LV3, COMPRESSED_BLOCK_LV3);
		copy(ScTags.ScBlocks.COMPRESSED_BLOCK_LV4, COMPRESSED_BLOCK_LV4);
		copy(ScTags.ScBlocks.COMPRESSED_BLOCK_LV5, COMPRESSED_BLOCK_LV5);
		copy(ScTags.ScBlocks.COMPRESSED_BLOCK, COMPRESSED_BLOCK);
		copy(ScTags.ScBlocks.COMPRESSED_COBBLESTONE, COMPRESSED_COBBLESTONE);
		copy(ScTags.ScBlocks.COMPRESSED_MOSSY_COBBLESTONE, COMPRESSED_MOSSY_COBBLESTONE);
		copy(ScTags.ScBlocks.COMPRESSED_STONE, COMPRESSED_STONE);
		copy(ScTags.ScBlocks.COMPRESSED_GRANITE, COMPRESSED_GRANITE);
		copy(ScTags.ScBlocks.COMPRESSED_ANDESITE, COMPRESSED_ANDESITE);
		copy(ScTags.ScBlocks.COMPRESSED_DIORITE, COMPRESSED_DIORITE);
		copy(ScTags.ScBlocks.COMPRESSED_BEDROCK, COMPRESSED_BEDROCK);
		copy(ScTags.ScBlocks.COMPRESSED_END_STONE, COMPRESSED_END_STONE);
		copy(ScTags.ScBlocks.COMPRESSED_OBSIDIAN, COMPRESSED_OBSIDIAN);
		copy(ScTags.ScBlocks.COMPRESSED_GLOWINGOBSIDIAN, COMPRESSED_GLOWINGOBSIDIAN);
		copy(ScTags.ScBlocks.COMPRESSED_CRYING_OBSIDIAN, COMPRESSED_CRYING_OBSIDIAN);
		copy(ScTags.ScBlocks.COMPRESSED_PRISMARINE, COMPRESSED_PRISMARINE);
		copy(ScTags.ScBlocks.COMPRESSED_DARK_PRISMARINE, COMPRESSED_DARK_PRISMARINE);
		copy(ScTags.ScBlocks.COMPRESSED_NETHERRACK, COMPRESSED_NETHERRACK);
		copy(ScTags.ScBlocks.COMPRESSED_GLOWSTONE, COMPRESSED_GLOWSTONE);
		copy(ScTags.ScBlocks.COMPRESSED_BLACKSTONE, COMPRESSED_BLACKSTONE);
		copy(ScTags.ScBlocks.COMPRESSED_CALCITE, COMPRESSED_CALCITE);
		copy(ScTags.ScBlocks.COMPRESSED_DEEPSLATE, COMPRESSED_DEEPSLATE);
		copy(ScTags.ScBlocks.COMPRESSED_COBBLED_DEEPSLATE, COMPRESSED_COBBLED_DEEPSLATE);
		copy(ScTags.ScBlocks.COMPRESSED_BASALT, COMPRESSED_BASALT);
		copy(ScTags.ScBlocks.COMPRESSED_TUFF, COMPRESSED_TUFF);
		copy(ScTags.ScBlocks.COMPRESSED_DRIPSTONE_BLOCK, COMPRESSED_DRIPSTONE_BLOCK);
		tag(STONE_CRAFTING_MATERIALS).add(
				COBBLESTONE,
				GRANITE,
				ANDESITE,
				DIORITE,
				END_STONE,
				NETHERRACK,
				BLACKSTONE,
				CALCITE,
				COBBLED_DEEPSLATE,
				BASALT,
				TUFF,
				DRIPSTONE_BLOCK
		);
		tag(COMPRESSED_STONE_MATERIAL).addTags(
				COMPRESSED_COBBLESTONE,
				COMPRESSED_GRANITE,
				COMPRESSED_ANDESITE,
				COMPRESSED_DIORITE,
				COMPRESSED_END_STONE,
				COMPRESSED_NETHERRACK,
				COMPRESSED_BLACKSTONE,
				COMPRESSED_CALCITE,
				COMPRESSED_COBBLED_DEEPSLATE,
				COMPRESSED_BASALT,
				COMPRESSED_TUFF,
				COMPRESSED_DRIPSTONE_BLOCK
		);
		tag(COMPRESSED_STONE_MATERIAL_LV1).add(
				ScItems.COMPRESSED_COBBLESTONE.getFirst().get(),
				ScItems.COMPRESSED_GRANITE.getFirst().get(),
				ScItems.COMPRESSED_ANDESITE.getFirst().get(),
				ScItems.COMPRESSED_DIORITE.getFirst().get(),
				ScItems.COMPRESSED_END_STONE.getFirst().get(),
				ScItems.COMPRESSED_NETHERRACK.getFirst().get(),
				ScItems.COMPRESSED_BLACKSTONE.getFirst().get(),
				ScItems.COMPRESSED_CALCITE.getFirst().get(),
				ScItems.COMPRESSED_COBBLED_DEEPSLATE.getFirst().get(),
				ScItems.COMPRESSED_BASALT.getFirst().get(),
				ScItems.COMPRESSED_TUFF.getFirst().get(),
				ScItems.COMPRESSED_DRIPSTONE_BLOCK.getFirst().get()
		);
		tag(COMPRESSED_STONE_MATERIAL_LV2).add(
				ScItems.COMPRESSED_COBBLESTONE.get(1).get(),
				ScItems.COMPRESSED_GRANITE.get(1).get(),
				ScItems.COMPRESSED_ANDESITE.get(1).get(),
				ScItems.COMPRESSED_DIORITE.get(1).get(),
				ScItems.COMPRESSED_END_STONE.get(1).get(),
				ScItems.COMPRESSED_NETHERRACK.get(1).get(),
				ScItems.COMPRESSED_BLACKSTONE.get(1).get(),
				ScItems.COMPRESSED_CALCITE.get(1).get(),
				ScItems.COMPRESSED_COBBLED_DEEPSLATE.get(1).get(),
				ScItems.COMPRESSED_BASALT.get(1).get(),
				ScItems.COMPRESSED_TUFF.get(1).get(),
				ScItems.COMPRESSED_DRIPSTONE_BLOCK.get(1).get()
		);
		tag(COMPRESSED_STONE_MATERIAL_LV3).add(
				ScItems.COMPRESSED_COBBLESTONE.get(2).get(),
				ScItems.COMPRESSED_GRANITE.get(2).get(),
				ScItems.COMPRESSED_ANDESITE.get(2).get(),
				ScItems.COMPRESSED_DIORITE.get(2).get(),
				ScItems.COMPRESSED_END_STONE.get(2).get(),
				ScItems.COMPRESSED_NETHERRACK.get(2).get(),
				ScItems.COMPRESSED_BLACKSTONE.get(2).get(),
				ScItems.COMPRESSED_CALCITE.get(2).get(),
				ScItems.COMPRESSED_COBBLED_DEEPSLATE.get(2).get(),
				ScItems.COMPRESSED_BASALT.get(2).get(),
				ScItems.COMPRESSED_TUFF.get(2).get(),
				ScItems.COMPRESSED_DRIPSTONE_BLOCK.get(2).get()
		);
		tag(COMPRESSED_STONE_MATERIAL_LV4).add(
				ScItems.COMPRESSED_COBBLESTONE.get(3).get(),
				ScItems.COMPRESSED_GRANITE.get(3).get(),
				ScItems.COMPRESSED_ANDESITE.get(3).get(),
				ScItems.COMPRESSED_DIORITE.get(3).get(),
				ScItems.COMPRESSED_END_STONE.get(3).get(),
				ScItems.COMPRESSED_NETHERRACK.get(3).get(),
				ScItems.COMPRESSED_BLACKSTONE.get(3).get(),
				ScItems.COMPRESSED_CALCITE.get(3).get(),
				ScItems.COMPRESSED_COBBLED_DEEPSLATE.get(3).get(),
				ScItems.COMPRESSED_BASALT.get(3).get(),
				ScItems.COMPRESSED_TUFF.get(3).get(),
				ScItems.COMPRESSED_DRIPSTONE_BLOCK.get(3).get()
		);
		tag(COMPRESSED_STONE_MATERIAL_LV5).add(
				ScItems.COMPRESSED_COBBLESTONE.get(4).get(),
				ScItems.COMPRESSED_GRANITE.get(4).get(),
				ScItems.COMPRESSED_ANDESITE.get(4).get(),
				ScItems.COMPRESSED_DIORITE.get(4).get(),
				ScItems.COMPRESSED_END_STONE.get(4).get(),
				ScItems.COMPRESSED_NETHERRACK.get(4).get(),
				ScItems.COMPRESSED_BLACKSTONE.get(4).get(),
				ScItems.COMPRESSED_CALCITE.get(4).get(),
				ScItems.COMPRESSED_COBBLED_DEEPSLATE.get(4).get(),
				ScItems.COMPRESSED_BASALT.get(4).get(),
				ScItems.COMPRESSED_TUFF.get(4).get(),
				ScItems.COMPRESSED_DRIPSTONE_BLOCK.get(4).get()
		);

		tag(COMPRESSED_STONE_FOOD_LV1).add(ScItems.COMPRESSED_STONICKERS_LV1.get());
		tag(COMPRESSED_STONE_FOOD_LV2).add(ScItems.COMPRESSED_STONICKERS_LV2.get());
		tag(COMPRESSED_STONE_FOOD_LV3).add(ScItems.COMPRESSED_STONICKERS_LV3.get());
		tag(COMPRESSED_STONE_FOOD_LV4).add(ScItems.COMPRESSED_STONICKERS_LV4.get());
		tag(COMPRESSED_STONE_FOOD_LV5).add(ScItems.COMPRESSED_STONICKERS_LV5.get());
		tag(COMPRESSED_STONE_FOOD).addTags(
				COMPRESSED_STONE_FOOD_LV1,
				COMPRESSED_STONE_FOOD_LV2,
				COMPRESSED_STONE_FOOD_LV3,
				COMPRESSED_STONE_FOOD_LV4,
				COMPRESSED_STONE_FOOD_LV5
		);
		tag(STONE_FOOD).add(
				ScItems.STONE_APPLE.get(),
				ScItems.STONE_BREAD.get(),
				ScItems.STONE_CARROT.get(),
				ScItems.STONE_KELP.get(),
				ScItems.STONE_MELON_SLICE.get(),
				ScItems.STONE_POTATO.get(),
				ScItems.STONE_HODGEPODGE.get(),
				ScItems.STONICKERS.get(),
				ScItems.STONE_COOKED_COD.get(),
				ScItems.STONE_COOKIE.get(),
				ScItems.STONE_COOKED_BEEF.get(),
				ScItems.STONE_GLOW_BERRIES.get(),
				ScItems.STONE_SWEET_BERRIES.get()
		).addTag(COMPRESSED_STONE_FOOD);
		tag(WOLF_FOOD).addTag(STONE_FOOD);

		copy(BlockTags.BASE_STONE_NETHER, BASE_STONE_NETHER);
		copy(BlockTags.BASE_STONE_OVERWORLD, BASE_STONE_OVERWORLD);
		copy(ScTags.ScBlocks.FALL_AWAY_STONE_NUGGET, FALL_AWAY_STONE_NUGGE);

		copy(ScTags.ScBlocks.STONE_DESTROYER_EFFECT_BLOCKS, STONE_DESTROYER_EFFECT_BLOCKS);
		copy(ScTags.ScBlocks.ADVANCEMENT_ROOT_BLOCK, ADVANCEMENT_ROOT_ITEM);
		copy(ScTags.ScBlocks.BREAKABLE_BY_STONE_NUGGET, BREAKABLE_BY_STONE_NUGGET);

		tag(Tags.Items.OBSIDIANS).add(
				ScItems.GLOWINGOBSIDIAN.get()
		);

		tag(STONE_NUGGET)
      .add(ScItems.STONE_NUGGET.get())
      .add(FLINT); //支持燧石

		tag(SLINGSHOT).add(
				ScItems.WOOD_SLINGSHOT.get(),
				ScItems.STONE_SLINGSHOT.get(),
				ScItems.IRON_SLINGSHOT.get(),
				ScItems.GOLD_SLINGSHOT.get(),
				ScItems.DIAMOND_SLINGSHOT.get(),
				ScItems.NETHERITE_SLINGSHOT.get()
		);

		tag(ItemTags.DURABILITY_ENCHANTABLE).addTag(SLINGSHOT);
    // 石质工作台&石头转换台
    copy(ScTags.ScBlocks.FUNCTIONAL_BLOCKS, ScTags.ScItems.FUNCTIONAL_BLOCKS);
    tag(ScTags.ScItems.FUNCTIONAL_BLOCKS).add(ScItems.STONE_CRAFTING_TABLE.get(), ScItems.STONE_CONVERTING_TABLE.get());

	}
}
